# Generated by Django 5.0.3 on 2025-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The actual content of the message.')),
                ('type', models.CharField(choices=[('user', 'User'), ('machine', 'Machine')], help_text='The origin of the message (user or machine).', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The exact moment the message was created.')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
