# Generated by Django 5.0.3 on 2025-05-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('keywords', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('votedEmails', models.TextField()),
                ('userEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
