# Generated by Django 5.0.3 on 2025-05-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votedEmails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
