# Generated by Django 5.0.3 on 2025-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answer_votedemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='userEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
