# Generated by Django 5.0.3 on 2025-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_alter_answer_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='topAnswer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
