# Generated by Django 5.0.3 on 2025-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dni', models.CharField(max_length=20, verbose_name='Document')),
                ('phone', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('admin', 'Admin')], default='worker', max_length=10)),
                ('password', models.CharField(default='default123', max_length=128, verbose_name='Password')),
                ('assigned_clients', models.ManyToManyField(blank=True, related_name='assigned_staff', to='client_user.client')),
            ],
        ),
    ]
