# Generated by Django 5.0.3 on 2025-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile picture of the staff member.', null=True, upload_to='staff_photos/'),
        ),
    ]
