# Generated by Django 5.0.3 on 2025-04-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelta', 'Resuelta')], default='pendiente', max_length=20)),
                ('urgencia', models.BooleanField(default=False)),
                ('archivo_adjuntado', models.FileField(blank=True, null=True, upload_to='documentos_incidencias/')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='pet.pet')),
                ('trabajador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to='staff.staff')),
            ],
        ),
    ]
