# Generated by Django 5.0.3 on 2025-05-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('staff', '0002_staff_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='The reason for the reassignment request.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='The current status of the reassignment request (pending, approved, rejected).', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the reassignment request was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the reassignment request was last updated.')),
                ('appointment', models.ForeignKey(help_text='The appointment being requested for reassignment.', on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_requests', to='appointment.appoinment')),
                ('requesting_worker', models.ForeignKey(help_text='The worker who is requesting the reassignment.', on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_requests_sent', to='staff.staff')),
                ('target_worker', models.ForeignKey(blank=True, help_text='The worker to whom the appointment is being requested to be reassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignment_requests_received', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Reassignment Request',
                'verbose_name_plural': 'Reassignment Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
