# Generated by Django 5.0.3 on 2025-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile picture of the client.', null=True, upload_to='client_photos/'),
        ),
    ]
