# Generated by Django 5.0.3 on 2025-05-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The exact moment the conversation was started.')),
                ('title', models.CharField(blank=True, help_text='An optional title for the conversation.', max_length=255, null=True)),
                ('client', models.ForeignKey(help_text='The client who owns this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='client_user.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
